export const SIGNIN_ACTION = "SIGNIN_ACTION"
export const SIGNUP_ACTION = "SIGNUP_ACTION"
export const LOGOUT_ACTION = "LOGOUT_ACTION"
export const FORGOT_ACTION = "FORGOT_ACTION"
export const LOGGEDIN_ACTION = "LOGGEDIN_ACTION"

// catagory
export const GETDATA_CATEGORY = "GETDATA_CATEGORY" 
export const ADD_CATEGORY = "ADD_CATEGORY" 
export const DELETE_CATEGORY = "DELETE_CATEGORY" 
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"